#!/usr/bin/env python3
"""
Generate jpfont.h: a tiny 1-bit bitmap font holding ONLY the Japanese (and any
other) glyphs used by the Open-EP Pet UI, rasterised from a system CJK font.

Each glyph is rendered into a square size*size cell (fullwidth), thresholded to
pure black/white (no anti-alias, for crisp e-paper output).  Re-run after
changing any UI string; the build embeds only what is listed in JOBS.

    python3 jpfont_gen.py            # writes jpfont.h next to this script
"""
import os
from PIL import Image, ImageFont, ImageDraw

FONT = "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"
OUT  = os.path.join(os.path.dirname(os.path.abspath(__file__)), "jpfont.h")

# (pixel size, text whose unique chars must be available at that size)
JOBS = [
    (20, "空腹元気気分"),        # stat labels
    (16, "おなかペット"),         # title
    (14, "エサあそぶそうじ"),      # buttons: Feed / Play / Clean
]

def render_glyph(ch, size):
    """Return (w, h, rows[]) 1-bit bitmap centred in a size*size cell."""
    font = ImageFont.truetype(FONT, size)
    img = Image.new("L", (size, size), 0)
    d = ImageDraw.Draw(img)
    x0, y0, x1, y1 = font.getbbox(ch)
    gw, gh = x1 - x0, y1 - y0
    pos = ((size - gw) // 2 - x0, (size - gh) // 2 - y0)
    d.text(pos, ch, font=font, fill=255)
    px = img.load()
    stride = (size + 7) // 8
    rows = []
    for y in range(size):
        row = bytearray(stride)
        for x in range(size):
            if px[x, y] >= 128:
                row[x >> 3] |= 0x80 >> (x & 7)
        rows.append(row)
    return size, size, rows

def main():
    glyphs = []            # (cp, size, w, h, rows)
    seen = set()
    for size, text in JOBS:
        for ch in text:
            key = (ord(ch), size)
            if key in seen:
                continue
            seen.add(key)
            w, h, rows = render_glyph(ch, size)
            glyphs.append((ord(ch), size, w, h, rows))
    glyphs.sort(key=lambda g: (g[1], g[0]))   # by (size, codepoint)

    blob, offs = bytearray(), []
    for cp, size, w, h, rows in glyphs:
        offs.append(len(blob))
        for row in rows:
            blob += row

    with open(OUT, "w") as f:
        f.write("/* generated by jpfont_gen.py - do not edit by hand */\n")
        f.write("#ifndef JPFONT_H\n#define JPFONT_H\n#include <stdint.h>\n\n")
        f.write("struct jpglyph { uint32_t cp; uint8_t size, w, h; uint16_t off; };\n\n")
        f.write("static const struct jpglyph jpglyphs[] = {\n")
        for (cp, size, w, h, _), off in zip(glyphs, offs):
            f.write(f"\t{{0x{cp:04X}, {size}, {w}, {h}, {off}}},\n")
        f.write("};\n#define JPGLYPH_COUNT (sizeof(jpglyphs)/sizeof(jpglyphs[0]))\n\n")
        f.write("static const uint8_t jpbits[] = {\n")
        for i in range(0, len(blob), 16):
            f.write("\t" + ",".join(f"0x{b:02X}" for b in blob[i:i+16]) + ",\n")
        f.write("};\n\n#endif /* JPFONT_H */\n")

    print(f"{len(glyphs)} glyphs, {len(blob)} bytes -> {OUT}")

if __name__ == "__main__":
    main()
