#!/usr/bin/env python3
"""Trace the dog*.png expression frames into 1-bit pixel-art sprites for the
pet UI.  Each frame is normalised by HEIGHT (scaled so the puppy is the same
size in every frame, centred, top-aligned) so expressions stay consistent.

    python3 sprite_gen.py            # preview only -> /tmp/sprite_frames.png
    python3 sprite_gen.py --emit     # also (re)write petsprite.h
"""
import os, sys
import numpy as np
from PIL import Image, ImageDraw

DIR = os.path.dirname(os.path.abspath(__file__))
OUT = DIR + "/petsprite.h"
TW = 62          # canvas width (wide enough for ears-up frames, no clipping)
H  = 56          # canvas height
PH = 52          # normalised puppy height -> every frame the same size, bigger
OY = 2           # top margin
TH_INK = 180

def gray(name):
    return np.asarray(Image.open(f"{DIR}/{name}").convert("L")).astype(int)

FRAMES = [   # (C name, source png, mode)  mode: 'box'=shared crop, 'fit'=own bbox
    ("pet_idle",      "dog.png",          "box"),
    ("pet_blink",     "dog_blink.png",    "box"),
    ("pet_happy",     "dog_happy.png",    "box"),
    ("pet_sad",       "dog_sad.png",      "box"),
    ("pet_eat",       "dog_eat.png",      "box"),
    ("pet_look",      "dog_look.png",     "box"),
    ("pet_surprised", "dog_surprised.png","box"),
]
BAND = (226, 599)   # puppy band, excludes the "PET" label below

def bbox(name):
    a = gray(name)[BAND[0]:BAND[1], :] < 150
    xs = np.where(a.any(0))[0]; ys = np.where(a.any(1))[0]
    return xs[0], BAND[0]+ys[0], xs[-1], BAND[0]+ys[-1]

def trace_norm(name):
    """Normalise by HEIGHT so every frame is the same size: scale the puppy's
    own bbox to PH tall, centre horizontally, top-align.  Wider frames (ears
    up) keep their full width without clipping."""
    x0,y0,x1,y1 = bbox(name); a = gray(name)[y0:y1+1, x0:x1+1]
    bw,bh = x1-x0+1, y1-y0+1
    s = PH/bh; tw = min(TW, int(round(bw*s)))
    ox = (TW-tw)//2
    g=[[0]*TW for _ in range(H)]
    for ty in range(PH):
        for tx in range(tw):
            yy0=int(ty/s); yy1=max(yy0+1,int((ty+1)/s))
            xx0=int(tx/s); xx1=max(xx0+1,int((tx+1)/s))
            if a[yy0:yy1, xx0:xx1].min() < TH_INK: g[OY+ty][ox+tx]=1
    return g

GRIDS = [(name, trace_norm(src)) for name, src, _ in FRAMES]

def render(g,scale=6):
    im=Image.new("L",(TW*scale,H*scale),255); d=ImageDraw.Draw(im)
    for y in range(H):
        for x in range(TW):
            if g[y][x]: d.rectangle([x*scale,y*scale,x*scale+scale-1,y*scale+scale-1],fill=0)
    return im
from PIL import ImageFont
F=ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",16)
ims=[(name,render(g)) for name,g in GRIDS]
cols=4; rows=(len(ims)+cols-1)//cols
cw=ims[0][1].width+8; chh=ims[0][1].height+22
m=Image.new("L",(cols*cw+8,rows*chh+8),255); dd=ImageDraw.Draw(m)
for i,(name,im) in enumerate(ims):
    r,c=divmod(i,cols); x=8+c*cw; y=8+r*chh
    dd.text((x,y),name.replace("pet_",""),font=F,fill=0); m.paste(im,(x,y+18))
m.save("/tmp/sprite_frames.png"); print("preview /tmp/sprite_frames.png")

def to_bytes(g):
    stride=(TW+7)//8; out=[]
    for y in range(H):
        for bx in range(stride):
            v=0
            for b in range(8):
                xx=bx*8+b
                if xx<TW and g[y][xx]: v|=0x80>>b
            out.append(v)
    return out
if "--emit" in sys.argv:
    def emit(f,name,g):
        b=to_bytes(g); f.write(f"static const uint8_t {name}[] = {{\n")
        for i in range(0,len(b),12): f.write("\t"+",".join(f"0x{v:02X}" for v in b[i:i+12])+",\n")
        f.write("};\n")
    with open(OUT,"w") as f:
        f.write("/* generated by sprite_gen.py from dog*.png - do not edit */\n#ifndef PETSPRITE_H\n#define PETSPRITE_H\n#include <stdint.h>\n")
        f.write(f"#define PET_W {TW}\n#define PET_H {H}\n#define PET_STRIDE (({TW}+7)/8)\n")
        for name,g in GRIDS: emit(f,name,g)
        f.write("#endif\n")
    print("wrote",OUT)
